repositories {
    maven { url = uri('https://central.sonatype.com/repository/maven-snapshots') }
    maven { url = uri('https://libraries.minecraft.net') }
}

dependencies {
    compileOnly libs.bungeecord.api
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}